Added logs to cluster extraction
rancher/norman pull request #428
Opened 2023-03-24 19:37 UTC by rmweir

2023-03-24 19:53 UTC, KevinJoiner requested changes
Is the desire to leave this in forever? I am concerned that there are healthy Rancher setups that will start spamming this message since we are not sure what causes it. Or can we assume that anytime clusterName is empty, something is not correct?

2023-03-24 19:53 UTC, KevinJoiner commented on controller/cluster_check.go
> +	logrus.Debugf("failed to extract cluster that the object [%s:%s] of kind [%s] belongs to", ns, name, kind)
nit: I fear that this makes it into production, and a user sees the logs and assumes that something in rancher is failing, causing them to raise a ticket.
```suggestion
	logrus.Debugf("unable to extract cluster that the object [%s:%s] of kind [%s] belongs to", ns, name, kind)
```

2023-03-24 19:53 UTC, KevinJoiner commented on controller/cluster_check.go
>  		return o.ObjClusterName() == cluster
```suggestion
		return clusterName == cluster
```

2023-03-24 20:13 UTC, rmweir commented
@KevinJoiner We are trying to figure out how often this happens. If it happens frequently then that is a problem. I don't think spam will be much of an issue since it's debug. The handler also have a built in backoff so it should be throttled.

2023-03-24 20:20 UTC, cbron approved these changes
lgtm, since it is debug only. Sort of sucks it will run for every case, but should be minimal.

2023-03-27 13:37 UTC, KevinJoiner approved these changes

2023-03-28 15:35 UTC, merged